export { Battle } from './battle';
export { loadBattleData, createPokemon, getWildData } from './data';
export { initBattleUI, loadPokemonSprites, renderBattleBg, renderEnemySprite, renderPlayerSprite, renderEnemyHUD, renderBattleText, loadTrainerIntroAssets, renderTrainerSpriteAt, renderPokeballs, getTrainerIntroLayout, createSilhouette } from './battle_ui';
export type { TrainerIntroAssets } from './battle_ui';
export { loadWildEncounters, tryWildEncounter } from './encounter';
export { calcExpGain, gainExperience, initExperience, expToNextLevel, totalExpForLevel } from './experience';
export { attemptCatch } from './catch';
export type { BallType, CatchResult } from './catch';
export { checkPreTurnStatus, tryInflictStatus, applyEndOfTurnDamage } from './status';
export { loadTrainerData, getTrainerClass } from './trainer_ai';
export type { TrainerClassData, TrainerPartyMember } from './trainer_ai';
export type { BattlePokemon, BattleState, PokemonSpecies, MoveData } from './types';
export { checkEvolutions, applyEvolution, getEvolutionMoves } from './evolution';
export type { EvolutionCandidate } from './evolution';
export { createVolatiles, resetVolatiles } from './volatiles';
export type { Volatiles } from './volatiles';
